backbone: resnet50
n_epochs: 70
scheduler: multisteplr
optim_mom: 0.9
lr_milestones:
  - 49
  - 63
sched_multistep_lr_gamma: 0.2
batch_size: 128
seed: 1993
SIZE: [256, 256]
MEAN: [0.485, 0.456, 0.406]
STD: [0.229, 0.224, 0.225]
TRANSFORM:
  - Resize:
      size: 256
      interpolation: 3
  - ToTensor
  - Normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
TEST_TRANSFORM:
  - Resize:
      size: 256
      interpolation: 3
  - CenterCrop:
      size: 256
  - ToTensor
  - Normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]