seq-cifar100:
  dataset_config: icarl
  optim_nesterov: True
  compute_theoretical_best: True
  use_original_icarl_transform: True
  2000:
    lr: 2

seq-cub200:
  dataset_config: icarl
  optim_nesterov: True
  compute_theoretical_best: True
  use_original_icarl_transform: False
  2000:
    lr: 2


seq-imagenet-r:
  dataset_config: icarl
  optim_nesterov: True
  compute_theoretical_best: True
  use_original_icarl_transform: False
  2000:
    lr: 2    


seq-cifar10:
  dataset_config: icarl
  optim_nesterov: True
  compute_theoretical_best: True
  use_original_icarl_transform: False
  2000:
    lr: 2    


